apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-form
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sahu04/student-form-gitops.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
