# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   type: LoadBalancer
#   selector: { app: frontend }
#   ports:
#   - port: 80
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
